Fix missing directory error when npm building
The full error was:
    Error: ENOENT: no such file or directory, open
    '/srv/src/kpi/jsapp/compiled/extracted-strings.json'