ci(openapi): fail CI job on drf-spectacular error DEV-2135 DEV-2182 (#7097)
### 💭 Notes

Note for myself: when a command is put inside an `if` condition, Bash
temporarily suspends `set -e`. It assumes you are manually handling the
failure.

### 👀 Preview steps

See the
[job](https://github.com/kobotoolbox/kpi/actions/runs/25922120403/job/76193612232?pr=7026)
of actual unhandled failure here at
https://github.com/kobotoolbox/kpi/pull/7026:
> Locally, this script is expected to be run from a container, for
example like this:
   cd kobo-install
   ./run.py -cf run --rm kpi ./scripts/generate_api.sh
Enabling Stripe for schema generation…
Stripe enabled: true
Generating v2 OpenAPI JSON schema with drf-spectacular…
Traceback (most recent call last):
File
"/opt/hostedtoolcache/Python/3.12.13/x64/lib/python3.12/site-packages/constance/base.py",
line 123, in __getattr__
    asyncio.get_running_loop()
RuntimeError: no running event loop

See the
[job](https://github.com/kobotoolbox/kpi/actions/runs/26575268831/job/78292784599?pr=7097)
of a WIP commit that fails and is handled, and job of this PR that
succeeds.

---------

Co-authored-by: Olivier Léger <olivierleger@gmail.com>