Squashed commit of the following:
commit 11ee6768e5656a008db3e88882a06ae7985708bf
Author: Rebecca Graber <becca.graber@kobotoolbox.org>
Date:   Thu Jan 16 08:47:09 2025 -0500

    feat(projectHistoryLogs): log new submissions (#5416)

    ### 📣 Summary
    Create logs when new submissions are added to projects.

    ### 👷 Description for instance maintainers
    Allow null user_uids in AuditLogs so we can log anonymous submissions.

    ### 💭 Notes
    We previously had no need for null users in audit logs because the
    actions we logged were all restricted to authenticated users, but since
    we allow anonymous submissions, we needed a way to log those.

    ### 👀 Preview steps

    Feature/no-change template:
    1. ℹ️ have an account and a project. Make sure the account username is
    not `admin` (see [this notion
    task](https://www.notion.so/kobotoolbox/Anonymous-submissions-dont-work-if-user-named-admin-owns-asset-1767e515f65480608dfcee76ba9b3710?pvs=4))
    2. Deploy the project
    3. Add a submission to the project
    4. Go to `api/v2/asset/<asset-uid>/history`
    5. 🟢 There should be a new project history log with
    `action='add-submission'` and all the usual metadata, plus
    ```
    "submission": {
        "submitted_by": "user1"
    }
    ```
    6. Enable submissions without username/email to the project
    7. To make sure you're submitting anonymously, copy and paste the enketo
    link into a new private tab and add a new submission
    8. 🟢 Reload the endpoint. There should be a new audit log with
    `action='add-submission'`
    a. The user should be
    `http://kf.kobo.local:8080/api/v2/users/AnonymousUser/`
      b. The user_uid will be the uid of the anonymous user in the database
      c. The username should be `AnonymousUser`
    d. The metadata should contain `{"submission": {"submitted_by":
    "AnonymousUser"}` in addition to the usual

commit bbfdaf10c45371d2632eff4cfff9d6a4d6d4f97e
Author: olive-KTB <olive.godswill@kobotoolbox.org>
Date:   Thu Jan 16 02:49:14 2025 +0100

    update gitlab-ci.yml

commit bc56f8fa5ab8509a9d8f504ec2eac8c60edaf199
Author: Akuukis <Akuukis@users.noreply.github.com>
Date:   Wed Jan 15 10:50:39 2025 +0200

    refactor(frontend): Mantine Component Library PoC (#5344)

    ### 💭 Notes

    Please read the PR commit-by-commit, here's a guide.

    1.
    [3105f47](https://github.com/kobotoolbox/kpi/pull/5344/commits/3105f47b0a524994b1ff541fa81a5ac863c7210c)
    Setup Mantine Component Library. Please install the new dependencies,
    and add recommended VSCode extensions.
    2.
    [453f2c1](https://github.com/kobotoolbox/kpi/pull/5344/commits/453f2c186b2854cbaada59aa41be8328e20a5fe6)
    Here's a preview that Mantine in general works, and API for the example
    Button is different but generally similar.

    | our button | Mantine default button |
    |--------|--------|
    |
    ![image](https://github.com/user-attachments/assets/1f3e5736-c5eb-4cbf-a56e-a393dab561d3)
    |
    ![image](https://github.com/user-attachments/assets/c8f2a9dc-cf1a-44c3-881a-ff05da433060)
    |

    ![image](https://github.com/user-attachments/assets/e2abe407-3113-4900-9027-43186137ce13)

    3.
    [d782e38](https://github.com/kobotoolbox/kpi/pull/5344/commits/d782e38a952645258485559f7386f9f241bdb8d1)
    Example of custom styled component, Button. IMHO achieves pixel-perfect
    match in storybook and example above, except for line breaks, spinner
    and hover animations. Click animation matches out of box. Icon-only
    buttons are omitted because Mantine uses a different component
    `IconAction` for those.

    | Original on left / Mantine implementation on right |
    | --- |
    |
    ![image](https://github.com/user-attachments/assets/9a58b7af-3ff4-4b18-995c-6c57ff4264cb)
    |

    5.
    [eaf45e3](https://github.com/kobotoolbox/kpi/pull/5344/commits/eaf45e3d3275098099a914d723f21f97ec2e17e1)
    Wrapped Button to add support for inbuilt Tooltip. No idea if we want to
    move forward with these two coupled, but I found it useful for
    comparison by re-implementing part of old Button behavior that's
    represented in storybook.

    | Original | Mantine implementation |
    | --- | --- |
    |
    ![image](https://github.com/user-attachments/assets/7bf2a504-902b-4801-a2dd-3e7648166316)
    |
    ![image](https://github.com/user-attachments/assets/41bc4dff-acf3-4328-ab6f-f7fcccbde20b)
    |

    ### 👀 Preview steps

    1. ℹ️ open Kobo home
    4. 🟢 [on main] notice the original "new" button
    6. 🟢 [on PR] notice the new "new" button with default mantine style,
    only slightly different

    ---------

    Co-authored-by: Leszek Pietrzak <leszek@magicznyleszek.xyz>
    Co-authored-by: Leszek <smutnyleszek@gmail.com>
    Co-authored-by: James Kiger <68701146+jamesrkiger@users.noreply.github.com>
    Co-authored-by: Paulo Amorim <pauloamorimbr@gmail.com>
    Co-authored-by: James Kiger <james.kiger@gmail.com>

commit 9598180d07afdc8e3ebe5f4e0a7e35e4a252fd1d
Author: Raj Patel <51355159+rajpatel24@users.noreply.github.com>
Date:   Wed Jan 15 13:29:03 2025 +0530

    fix!: reject duplicate submissions (#5047)

    ## Summary
    Implemented logic to detect and reject duplicate submissions.

    ## Description

    We have identified a race condition in the submission processing that
    causes duplicate submissions with identical UUIDs and XML hashes. This
    issue is particularly problematic under conditions with multiple remote
    devices submitting forms simultaneously over unreliable networks.

    To address this issue, a PR has been raised with the following proposed
    changes:

    - Race Condition Resolution: A locking mechanism has been added to
    prevent the race condition when checking for existing instances and
    creating new ones. This aims to eliminate duplicate submissions.

    - UUID Enforcement: Submissions without a UUID are now explicitly
    disallowed. This ensures that every submission is uniquely identifiable
    and further mitigates the risk of duplicate entries.

    - Introduction of `root_uuid`:

    - To ensure a consistent submission UUID throughout its lifecycle and
    prevent duplicate submissions with the same UUID, a new `root_uuid`
    column has been added to the `Instance` model with a unique constraint
    (`root_uuid` per `xform`).

    - If the `<meta><rootUuid>` is present in the submission XML, it is
    stored in the `root_uuid` column.

    - If `<meta><rootUuid>` is not present, the value from
    `<meta><instanceID>` is used instead.

    - This approach guarantees that the `root_uuid` remains constant across
    the lifecycle of a submission, providing a reliable identifier for all
    instances.

    - UUID Handling Improvement: Updated the logic to strip only the `uuid:`
    prefix while preserving custom, non-UUID ID schemes (e.g.,
    domain.com:1234). This ensures compliance with the OpenRosa spec and
    prevents potential ID collisions with custom prefixes.

    - Error Handling:
    - 202 Accepted: Returns when content is identical to an existing
    submission and successfully processed.
    - 409 Conflict: Returns when a duplicate UUID is detected but with
    differing content.

    These changes should improve the robustness of the submission process
    and prevent both race conditions and invalid submissions.

    ## Notes

    - Implemented a fix to address the race condition that leads to
    duplicate submissions with the same UUID and XML hash.
    - Incorporated improvements from existing work, ensuring consistency and
    robustness in handling concurrent submissions.
    - The fix aims to prevent duplicate submissions, even under high load
    and unreliable network conditions.

    ## Related issues

    Supersedes
    [kobotoolbox/kobocat#876](https://github.com/kobotoolbox/kobocat/pull/876)
    and https://github.com/kobotoolbox/kobocat/pull/859

    ---------

    Co-authored-by: Olivier Leger <olivierleger@gmail.com>

commit d22b8b5053f707c9c41c41641b178de7e335fa5e
Merge: 89bd9b796 b4aa1b750
Author: John N. Milner <john@tmoj.net>
Date:   Tue Jan 14 15:20:49 2025 -0500

    Merge remote-tracking branch 'origin/release/2.024.36'

commit 89bd9b7968ac89bdb2d7ed8f889fb2a93aa6e944
Author: Rebecca Graber <becca.graber@kobotoolbox.org>
Date:   Tue Jan 14 15:11:37 2025 -0500

    fix(auditLogs): correctly serialize audit logs from deleted users (#5418)

    ### 📣 Summary
    Fixes a 500 error from the various audit log endpoints when there are
    actions by deleted users.

    ### 📖 Description
    Return empty user and username fields in the response if the user was
    deleted after the log was created. This applies to `/api/v2/audit-logs`,
    `api/v2/assets/<uid>/history`, and `api/v2/project-history-logs`.

    ### 💭 Notes
    Small fix in the serializer. Also updates the ProjectHistoryLog
    serializer to inherit from the AuditLogSerializer so we don't have to
    duplicate the method fields.

    ### 👀 Preview steps

    Bug template:
    1. ℹ️ have a super user account and a project
    2. Create a new user (user1) and give them the `Edit Form` permission on
    the project.
    3. Log in as user1 and make an edit to the project.
    4. Log out user1 and log back in as the super user
    5. Delete user1. You can do this from the admin page if you delete the
    user from the User list, then from the Trash Bin.
    6. Go to:
      a. `api/v2/audit-logs`
      b. `api/v2/project-history-logs`
      c. `api/v2/assets/<uid>/history`
    7. 🔴 [on main] All will return a 500 error (`AttributeError: 'NoneType'
    object has no attribute 'username'`)
    8. 🟢 [on PR] The endpoint will return the expected logs. For all user1's
    actions, the user and username fields will be empty. but the user_uid
    should still refer to the old user.

commit b4aa1b750e774465cc46b3cbe9004c8db9f5be4c
Author: jnm <john@tmoj.net>
Date:   Tue Jan 14 15:01:18 2025 -0500

    feat: export background-geopoint as GPS field (#5420)

    See kobotoolbox/formpack#327. This change just updates the formpack
    commit hash used by KPI

commit dddd6198cc30b57140fcffa7014e7399c756ab03
Author: Olivier Léger <olivierleger@gmail.com>
Date:   Tue Jan 14 14:10:31 2025 -0500

    fix: catch additional XLSForm validation errors during deployment (#5419)

    ### 📣 Summary
    Enhanced error handling to catch more validation errors in XLSForm
    during deployment.

    ### 📖 Description
    Validation error handling for XLSForm deployment has been enhanced to
    catch a wider range of issues. This prevents the display of a generic
    500 error in the deployment modal and instead returns the explicit error
    message.

    ### Notes
    Supersedes #5417, #5411 and #5403

commit 9189ac979e9db4c65696b36b94fa6094966b3fda
Author: Olivier Léger <olivierleger@gmail.com>
Date:   Tue Jan 14 09:40:34 2025 -0500

    fix: handle case sensitivity for "Settings" sheet name with explicit error TASK-1353 (#5417)

    ### 📣 Summary
    Improved error handling for case-sensitive "Settings" sheet names.

    ### 📖 Description
    This update addresses an issue where a sheet named "Settings" with
    uppercase or mixed case letters causes unexpected behavior. An explicit
    error message is now raised to alert users of the case sensitivity,
    ensuring they can resolve the issue easily.

commit 8e8d6bbe8be3be7f9616830880f620f7226a75fe
Author: Rebecca Graber <becca.graber@kobotoolbox.org>
Date:   Mon Jan 13 15:02:04 2025 -0500

    test: rename admin user in fixture (#5415)

    ### 💭 Notes
    Developer-facing changes only. Changes the username of the admin user to
    `adminuser` in preparation for disallowing the name `admin` as part of
    https://www.notion.so/kobotoolbox/Anonymous-submissions-dont-work-if-user-named-admin-owns-asset-1767e515f65480608dfcee76ba9b3710